on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_37334546
        password: ${{ secrets.ftp_password }}
        local-dir: ./
        server-dir: /htdocs/

    - name: ğŸ› ï¸ Verify and Set Permissions
      run: |
        sshpass -p "${{ secrets.ftp_password }}" ssh -o StrictHostKeyChecking=no if0_37334546@ftpupload.net << 'EOF'
        mkdir -p /htdocs
        chmod -R 755 /htdocs
        EOF

    - name: ğŸ› ï¸ Install Composer
      run: sudo apt-get update && sudo apt-get install -y composer

    - name: ğŸ› ï¸ Install Dependencies
      run: |
        sshpass -p "${{ secrets.ftp_password }}" ssh -o StrictHostKeyChecking=no if0_37334546@ftpupload.net << 'EOF'
        cd /htdocs
        composer install
        EOF
