on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4

    - name: ğŸ—‘ï¸ Remove old vendor files
      run: |
        curl -u if0_37334546:${{ secrets.ftp_password }} ftp://ftpupload.net --quote "DELE /htdocs/vendor.zip"
        curl -u if0_37334546:${{ secrets.ftp_password }} ftp://ftpupload.net --quote "MLSD /htdocs/vendor" | grep -v "vendor.zip" | awk '{print $9}' | xargs -I {} curl -u if0_37334546:${{ secrets.ftp_password }} ftp://ftpupload.net --quote "DELE /htdocs/vendor/{}"
        curl -u if0_37334546:${{ secrets.ftp_password }} ftp://ftpupload.net --quote "RMD /htdocs/vendor"

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_37334546
        password: ${{ secrets.ftp_password }}
        local-dir: ./
        server-dir: /htdocs/