on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_37334546
        password: ${{ secrets.ftp_password }}
        local-dir: ./
        server-dir: /htdocs/

    - name: ğŸ“¦ Upload vendor.zip
      run: |
        curl -T vendor.zip ftp://if0_37334546:${{ secrets.ftp_password }}@ftpupload.net/htdocs/vendor.zip

    - name: ğŸ› ï¸ Unzip vendor.zip
      run: |
        sshpass -p "${{ secrets.ftp_password }}" ssh -o StrictHostKeyChecking=no if0_37334546@ftpupload.net << 'EOF'
        cd /htdocs
        unzip vendor.zip
        rm vendor.zip
        EOF
