on: push
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4

    - name: ğŸ§¹ Clean up old dependencies
      run: |
        rm -rf vendor composer.lock

    - name: ğŸ“¦ Install Composer Dependencies
      run: |
        composer install --no-dev --no-cache --no-scripts

    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_37334546
        password: ${{ secrets.ftp_password }}
        local-dir: ./  # DiretÃ³rio local onde os arquivos estÃ£o
        server-dir: /htdocs/  # DiretÃ³rio no servidor FTP onde os arquivos devem ser enviados
        only-new: true  # Adiciona essa linha para enviar apenas arquivos novos
